### ISSUE TITLE
The live demo "gifie" fails with 404 for jquery.knob.js

### ISSUE THREAD

**Issue by shooshx** [eirikb/gifie#3]
http://eirikb.github.io/gifie/

doesn't work
chrome console has this error:

```

http://anthonyterrien.com/js/jquery.knob.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:26 Uncaught TypeError: $loader.knob is not a function
```

**Comment by eirikb** [comment]
Thanks. Will look into it

**Comment by leonardobaggio** [comment]
The "http://anthonyterrien.com/js/jquery.knob.js" is down.Maybe a CDN could help to avoid this. 

Found this one, need only to check if this is the right version:

https://cdnjs.cloudflare.com/ajax/libs/jQuery-Knob/1.2.13/jquery.knob.min.js
https://cdnjs.com/libraries/jQuery-Knob
